### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by donn** [ucb-bar/chisel-template#27]
The three-clause BSD license is nowhere in this repository despite constant `See LICENSE for license details.` action going on in the source files. I am assuming this is an omission, could the maintainer please clarify?

**Comment by ucbjrl** [comment]
Thanks for pointing this out. We'll add a BSD 3-clause license.

**Comment by ucbjrl** [comment]
#29 (0f4f4c5) adds an un-license to the README.md and comments have been changed to refer to it.
