### ISSUE TITLE
failed to build the GCD module

### ISSUE THREAD

**Issue by zhutmost** [ucb-bar/chisel-template#35]
Hi developers,

I'm trying to build the GCD module as follows,
```scala
package gcd

import chisel3._

/**
  * Compute GCD using subtraction method.
  * Subtracts the smaller from the larger until register y is zero.
  * value in register x is then the GCD
  */
class GCD extends Module {
  val io = IO(new Bundle {
    val value1        = Input(UInt(16.W))
    val value2        = Input(UInt(16.W))
    val loadingValues = Input(Bool())
    val outputGCD     = Output(UInt(16.W))
    val outputValid   = Output(Bool())
  })

  val x  = Reg(UInt())
  val y  = Reg(UInt())

  when(x > y) { x := x - y }
    .otherwise { y := y - x }

  when(io.loadingValues) {
    x := io.value1
    y := io.value2
  }

  io.outputGCD := x
  io.outputValid := y === 0.U
}
```
But it failed for some bugs I cannot solve. Here is the log of builder.
![image](https://user-images.githubusercontent.com/20497382/44276503-3d1fbc80-a27a-11e8-8c94-8b84dd172152.png)

Thank you.

**Comment by edwardcwang** [comment]
Can you show us the `Dragonfly.scala` file?

**Comment by ucbjrl** [comment]
This looks like the Scala 2.12 problem with anonymous bundles.

You need to copy the relevant sections of chisel-template/build.sbt that
set the appropriate Scala compiler options to work around this.

**Comment by zhutmost** [comment]
Thank you, ucbjrl. I bumped the scalaVersion to 2.11.12. and solved.
This issue can be closed.
